<a href="https://colab.research.google.com/github/AMANVISHWAKARMA27/Age-Calculator/blob/main/Multivariate_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [ ]:
#filling the missing values
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
reg = linear_model.LinearRegression()
# fit() method is used to train the model using the data set
reg.fit(df[['area', 'bedrooms','age']], df.price)

LinearRegression()

In [ ]:
reg.coef_


array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_

383724.9999999998

In [ ]:
reg.predict([[3000, 3 , 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [ ]:
137.25*3000 - 26025*3 - 6825*40 + 383724.9999999998

444399.9999999998

PRACTICE EXERCISE

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df.experience.unique()

array([nan, 'five', 'two', 'seven', 'three', 'ten', 'eleven'],
      dtype=object)

In [ ]:
import math

a = 0
for i in df.experience:
  if i == "five":
    a = 5
  elif i == 'two':
    a = 2
  elif i == 'seven':
    a = 7
  elif i == 'three':
    a = 3
  elif i == 'ten':
    a = 10
  elif i == 'eleven':
    a = 11
  else:
    a = 0
  df['experience'] = df['experience'].replace(i,a)



In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [ ]:
import math
median_testScore = df['test_score(out of 10)'].median()
median_testScore

8.0

In [ ]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_testScore)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [ ]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [ ]:
reg.intercept_

17737.263464337688

In [ ]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])